version: '3.4'

services:
  mysql:
    image: mysql:5.7.28
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes: 
      - mysql_data:/var/lib/mysql
    networks: 
      - backend-network
  
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    networks:
      - frontend-network 
      - backend-network
  
  wordpress:
    image: wordpress
    ports: 
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mysqlc
      - WORDPRESS_DB_NAME=wp_database
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    volumes: 
      - wordpress_data:/var/www/html
    networks:
      - frontend-network
      - backend-network